# docker compose -f docker-compose.rocm.yaml build backend && docker compose up --build -d && docker compose logs -f backend

name: ai-rag-helper
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PYTHON_VERSION: ${PYTHON_VERSION:-3.14}
        PYTHON_APP: ${PYTHON_APP:-}
        REPO_BUILDER: ${REPO_BUILDER:-rocm/pytorch:latest}
        EXTRA: ${EXTRA:-docker}
        UV_PYTHON: ${UV_PYTHON:-}
        APP_PORT: ${APP_PORT:-8000}
    volumes:
#      - ./src:/app/src
      - ./data/models:/app/data/models
      - uv_cache:/root/.cache/uv
#      - models:/app/data/models
    ports:
      - "${APP_PORT:-8000}:${APP_PORT:-8000}"
    depends_on:
      - redis
    env_file:
      - .env
    devices:
      - /dev/kfd
      - /dev/dri
    security_opt:
      - seccomp=./dockers/rocm-seccomp.json


volumes:
  redis_data:
  models:
  uv_cache:
